### ISSUE TITLE
Filter with id  does not exist.

### ISSUE THREAD

**Issue by stevensf1998** [valory-xyz/mech#183]
Encountered a problem where, when i try "Run the Mech as a standalone agent" and "Run the Mech as an agent service"

<img width="656" alt="Screenshot 2024-03-01 at 6 00 17 PM" src="https://github.com/valory-xyz/mech/assets/105898645/106e370b-e5cd-4ee3-8599-0f2b5a74b015">

I have filter with id xxxx does not exist.

How do i overcome this issues, and what is the number? isit a block number?

**Comment by Adamantios** [comment]
Hey, please take a look at https://github.com/valory-xyz/trader/issues/129#issuecomment-1816090556.

I would suggest using a nodies RPC which usually does not misbehave, and when this happens it auto resolves after ~15 minutes.
