### ISSUE TITLE
Create a new parameter to store config for prediction tools

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/mech#96]
https://github.com/valory-xyz/mech/pull/95#pullrequestreview-1556567471

**Comment by 0xArdi** [comment]
I think it would complicate things way more than the current setup, right now we just pass the api keys to the tool, changing this would mean either:
- we pass an additional params dict to the tool (would need changing all the tools)
- we extend api keys with params at run time (to avoid changing all the tools)

I think it might make sense to add params to the tools at some point, but at this point I think its not worth it.
